<a href="https://colab.research.google.com/github/AJihwan/2024-intro-DA-code/blob/main/w04_3_python_numpy_function2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 3 내장함수 zeros()와 ones(), empty()

## 원소가 모두 0인 배열을 생성하는 zeros()

In [1]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [2]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
a.dtype


dtype('float64')

In [4]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [5]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [6]:
b.shape

(2, 1)

## 원소가 모두 1인 배열을 생성하는 ones()

In [7]:
import numpy as np

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
import numpy as np

np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 대각선 원소가 모두 1인 2차원 배열을 생성하는 eye()

In [9]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [10]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [12]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
a = np.eye(3,4,1)

In [14]:
a = np.eye(3,4,-1)

## 원소가 모두 1인 배열을 생성하는 full()

In [15]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible wit

In [16]:
import numpy as np

np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [17]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:
np.full([3,4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [19]:
np.full([4,3],fill_value=np.arange(4).reshape(4,1))


array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

## 원소가 모두 1인 배열을 생성하는 empty()

In [20]:
import numpy as np

np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [21]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [22]:
np.empty([2,3], dtype=int)

array([[    102010254445177,                   0, 2308776984846671930],
       [                 33,     101991799129440,     135444960369904]])

## 원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like()

In [23]:
import numpy as np

a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

## 원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [25]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()

In [26]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])