<a href="https://colab.research.google.com/github/AJihwan/2024-intro-DA-code/blob/main/w05_3_array_stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SECTION 01 배열 결합

## numpy.vstack()

In [137]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [138]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [139]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [140]:
c = np.arange(20,24).reshape(2,2)

In [141]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [142]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [143]:
d = np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [144]:
d = np.array([100,200,300])
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [145]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

## numpy.hstack()

In [146]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [147]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [149]:
np.hstack(((a,b)))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [150]:
c = np.array([[10,20],[30,40]])
c

array([[10, 20],
       [30, 40]])

In [151]:
np.hstasck((a,c))

AttributeError: module 'numpy' has no attribute 'hstasck'

In [152]:
np.hstack((np.arange(3),np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

## numpy.column_stack

In [153]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [154]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [155]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [156]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [157]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [158]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [159]:
y[:,np.newaxis]

array([[4],
       [5],
       [6]])

In [160]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [161]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [162]:
np.column_stack == np.hstack

False

## numpy.row_stack()

In [163]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [164]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [165]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [166]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [167]:
a = np.array([4.,2.,1.])
b = np.array([3.,8.,7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [168]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [169]:
np.row_stack == np.vstack

True

## numpy.concatenate()

In [170]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

In [171]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [172]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [173]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [174]:
import numpy as np

x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [176]:
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [177]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [178]:
np.concatenate((x,y,z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [179]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [180]:
np.concatenate((x,y),axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

##numpy.stack()

In [181]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [182]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [183]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [185]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [187]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

## np stack()로 배열 x,y,z를 0번 축 방향으로 합치기

In [188]:
ax0 = np.stack((x,y,z),axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [189]:
ax0.shape

(3, 2, 3)

In [190]:
ax1 = np.stack((x,y,z),axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [191]:
ax1.shape

(2, 3, 3)

In [192]:
ax2 = np.stack((x,y,z),axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [193]:
ax2.shape

(2, 3, 3)

## np.stack(axis=2) 분해

In [194]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [195]:
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [196]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [197]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [198]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [199]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [200]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [201]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

## 배열의 결합 비교 column_stack()과 hstack()

In [202]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [203]:
c= np.arange(1,6,2)
c

array([1, 3, 5])

In [204]:
c[:,np.newaxis]

array([[1],
       [3],
       [5]])

In [205]:
np.hstack((a,c[:,np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [206]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [208]:
np.hstack((a,np.expand_dims(c,axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [209]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

## row_stack()과 vstack()

In [210]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [211]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [212]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [213]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

## np.c_[]와 np.column_stack()

In [214]:
help(np.c_)

Help on CClass in module numpy.lib.index_tricks object:

class CClass(AxisConcatenator)
 |  Translates slice objects to concatenation along the second axis.
 |  
 |  This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
 |  useful because of its common occurrence. In particular, arrays will be
 |  stacked along their last axis after being upgraded to at least 2-D with
 |  1's post-pended to the shape (column vectors made out of 1-D arrays).
 |  
 |  See Also
 |  --------
 |  column_stack : Stack 1-D arrays as columns into a 2-D array.
 |  r_ : For more detailed documentation.
 |  
 |  Examples
 |  --------
 |  >>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
 |  array([[1, 4],
 |         [2, 5],
 |         [3, 6]])
 |  >>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
 |  array([[1, 2, 3, ..., 4, 5, 6]])
 |  
 |  Method resolution order:
 |      CClass
 |      AxisConcatenator
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |     

In [220]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [221]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [222]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [223]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [224]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

## np.r_[] 개요

In [225]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [227]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [228]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [229]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [230]:
np.r_[3:10:3,[0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [231]:
np.r_[-1:1:6j, [0]*2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [232]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

## np.r_['i, j, k', a , b]

In [233]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [234]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [235]:
np.r_['0',a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [236]:
np.r_['-1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [237]:
np.r_['1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [238]:
np.r_['0,2',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [239]:
np.r_['0,3',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [240]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [241]:
np.r_['0,3,0',[1,2,3],[4,5,6]].shape

(6, 1, 1)

In [242]:
np.r_['0,3,1',[1,2,3],[4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [243]:
np.r_['0,3,1',[1,2,3],[4,5,6]].shape

(2, 3, 1)

In [244]:
np.r_['0,3,2',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

## 여러 1차원 배열을 수평 방향으로 합치는 방법

In [245]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)
print(b.shape)

(3,)
(3,)


In [246]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [247]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [248]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

## 여러 1차원 배열을 수직 방향으로 합치는 방법

In [249]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [250]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [251]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [252]:
np.r_[a[np.newaxis,:],b[np.newaxis,:]]

array([[1, 2, 3],
       [4, 5, 6]])

In [253]:
np.concatenate((a[np.newaxis,:],b[np.newaxis,:]))

array([[1, 2, 3],
       [4, 5, 6]])

## 여러 1차원 배열을 행으로 확장해 수평 방향으로 합치는 방법

In [254]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [255]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [256]:
np.hstack((a[:,np.newaxis],b[:,np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [257]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [258]:
np.concatenate(((a[:,np.newaxis],b[:,np.newaxis])),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])